name: Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore FreshMvvm/src/FreshMvvm/FreshMvvm.csproj 
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish FreshMvvm.ashjit
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: FreshMvvm/src/FreshMvvm/FreshMvvm.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
